friendship:
    path:     /
    defaults: { _controller: "ProjectInsectBundle:Friendship:index" }

friendship_show:
    path:     /{id}/show
    defaults: { _controller: "ProjectInsectBundle:Friendship:show" }

friendship_new:
    path:     /new
    defaults: { _controller: "ProjectInsectBundle:Friendship:new" }

friendship_create:
    path:     /create
    defaults: { _controller: "ProjectInsectBundle:Friendship:create" }
    methods:  POST

friendship_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjectInsectBundle:Friendship:edit" }

friendship_update:
    path:     /{id}/update
    defaults: { _controller: "ProjectInsectBundle:Friendship:update" }
    methods:  [POST, PUT]

friendship_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjectInsectBundle:Friendship:delete" }
    methods:  [POST, DELETE]
